"""scripts/render.py: the card block, the two tables and the placements it builds."""

from __future__ import annotations

import contextlib
import copy
import io
import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from tests.support import FIXTURE_CARD, FIXTURE_VOICE, HERE, build_repo, layout, model_files, provider_file, render, voice_card, write


def quiet_main(*args: str) -> int:
    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
        return render.main(list(args))


def card(**changes: object) -> dict:
    data = copy.deepcopy(FIXTURE_CARD)
    data.update(changes)
    return data


def field(block: str, name: str) -> str:
    """The value of one row of a card block."""
    prefix = f"| {name} | "
    return next(line for line in block.split("\n") if line.startswith(prefix))[len(prefix):-2]


TIERS = json.loads((HERE / "fixtures" / "tiers.json").read_text(encoding="utf-8"))


class CardBlockTest(unittest.TestCase):
    def test_the_rows_for_the_fixture_card(self) -> None:
        block = render.render_card_block(card())
        self.assertTrue(block.startswith("<!-- Generated by scripts/render.py from example-model-1.json;"))
        self.assertIn("| Field | Value |\n| --- | --- |\n", block)
        expected = {
            "Id": "`example-model-1`", "Maker": "Example Lab", "Class": "Example Pro", "Generation": "1",
            "Released": "2026-09-01", "Status": "ga", "Weights": "closed", "Access": "Example API; Example CLI",
            "Context window": "1M tokens", "Max output": "128k tokens", "Modalities": "input text, image; output text",
            "Reasoning control": "effort: low, medium, high (default medium)",
            "Price": "$5 in / $25 out per Mtok; cached input $0.5; list price, standard tier",
            "Key benchmarks": "SWE-Bench Pro (Scale, public V2): 70.0 (high, Example CLI, independent) "
                              "[scale-swe-pro-v2](https://example.com/leaderboard)",
            "Other benchmarks": "Aider polyglot: 80.0 (maker) [scale-swe-pro-v2](https://example.com/leaderboard)",
            "Prompting guides": "[example.com/prompting](https://example.com/prompting)",
            "System card": "[example.com/system-card](https://example.com/system-card)",
            "Model page": "unknown", "Card checked": "2026-10-03",
        }
        for name, value in expected.items():
            self.assertEqual(field(block, name), value, name)
        self.assertIn("model_page: none found", field(block, "Not found"))

    def test_the_block_is_a_comment_and_one_table_of_twenty_rows(self) -> None:
        block = render.render_card_block(card())
        self.assertTrue(block.endswith(" |\n"))
        self.assertEqual(block.count("\n"), 3 + 20)

    def test_two_differently_qualified_results_stay_distinguishable(self) -> None:
        subset = {"name": "SWE-Bench Pro (Anthropic 478-problem subset, near-saturated)", "score": 95.3, "setting": "high",
                  "harness": None, "measured_by": "maker", "source": "maker-post", "read": "2026-10-03"}
        public = {"name": "SWE-Bench Pro (Scale, public V2)", "score": 98.0, "setting": "xhigh", "harness": "Claude Code",
                  "measured_by": "independent", "source": "scale-swe-pro-v2", "read": "2026-10-03"}
        sources = FIXTURE_CARD["sources"] + [
            {"id": "maker-post", "url": "https://example.com/maker-post", "read": "2026-10-03", "kind": "L", "quote": None}
        ]
        cells = [
            field(render.render_card_block(card(benchmarks=[bench], sources=sources)), "Key benchmarks")
            for bench in (subset, public)
        ]
        self.assertIn("SWE-Bench Pro (Anthropic 478-problem subset, near-saturated): 95.3 (high, maker)", cells[0])
        self.assertIn("SWE-Bench Pro (Scale, public V2): 98.0 (xhigh, Claude Code, independent)", cells[1])
        both = field(render.render_card_block(card(benchmarks=[subset, public], sources=sources)), "Key benchmarks")
        self.assertIn("near-saturated): 95.3", both)
        self.assertIn("(Scale, public V2): 98.0", both)
        self.assertIn("[maker-post](https://example.com/maker-post)", both)
        self.assertIn("[scale-swe-pro-v2](https://example.com/leaderboard)", both)

    def test_key_benchmarks_come_in_the_order_of_the_list_and_the_rest_follow(self) -> None:
        second = {"name": "Terminal-Bench 4.0", "score": 40.0, "setting": None, "harness": None,
                  "measured_by": "independent", "source": "scale-swe-pro-v2", "read": "2026-10-03"}
        block = render.render_card_block(card(benchmarks=[second, *FIXTURE_CARD["benchmarks"]]))
        key = field(block, "Key benchmarks")
        self.assertLess(key.index("SWE-Bench Pro"), key.index("Terminal-Bench 4.0"))
        self.assertNotIn("Aider", key)
        self.assertNotIn("Terminal-Bench", field(block, "Other benchmarks"))

    def test_a_benchmark_without_a_score_is_left_out(self) -> None:
        bench = [dict(FIXTURE_CARD["benchmarks"][0], score=None)]
        block = render.render_card_block(card(benchmarks=bench))
        self.assertEqual(field(block, "Key benchmarks"), "none recorded")
        self.assertEqual(field(block, "Other benchmarks"), "none recorded")

    def test_a_reasoning_control_that_is_null_reads_unknown(self) -> None:
        block = render.render_card_block(card(reasoning={"control": None, "levels": [], "default": None}))
        self.assertEqual(field(block, "Reasoning control"), "unknown")

    def test_a_source_url_with_parentheses_keeps_the_link_whole(self) -> None:
        sources = [dict(FIXTURE_CARD["sources"][0], url="https://example.com/a_(b)")]
        self.assertIn("(https://example.com/a_%28b%29)", render.render_card_block(card(sources=sources)))

    def test_unknown_values_say_so(self) -> None:
        bare = card(context_window=None, max_output=None, pricing_usd_per_mtok=None, reasoning=None, benchmarks=[],
                    modalities=None, generation=None, weights=None, released=None, access=[], prompting_guides=[],
                    system_card=None, unknown=[])
        block = render.render_card_block(bare)
        for name in ("Context window", "Max output", "Modalities", "Reasoning control", "Price", "Generation", "Weights",
                     "Released", "Access", "Prompting guides", "System card", "Model page"):
            self.assertEqual(field(block, name), "unknown", name)
        self.assertEqual(field(block, "Not found"), "nothing")

    def test_retirement_date_shows_in_the_status(self) -> None:
        block = render.render_card_block(card(status="retiring", retires="2027-01-31"))
        self.assertEqual(field(block, "Status"), "retiring (retires 2027-01-31)")

    def test_a_retirement_date_before_the_check_date_shows_as_retired(self) -> None:
        block = render.render_card_block(card(status="retiring", retires="2026-09-14", checked="2026-10-03"))
        self.assertEqual(field(block, "Status"), "retired 2026-09-14")
        same_day = render.render_card_block(card(status="retiring", retires="2026-10-03", checked="2026-10-03"))
        self.assertEqual(field(same_day, "Status"), "retiring (retires 2026-10-03)")

    def test_pipes_in_text_are_escaped(self) -> None:
        self.assertEqual(field(render.render_card_block(card(maker="A | B")), "Maker"), "A \\| B")

    def test_a_price_missing_one_side_reads_unknown(self) -> None:
        pricing = {"input": 1.0, "output": None, "cached_input": None, "notes": None}
        self.assertEqual(field(render.render_card_block(card(pricing_usd_per_mtok=pricing)), "Price"), "unknown")

    def test_a_text_model_shows_no_voice_row(self) -> None:
        block = render.render_card_block(card())
        for name, _ in render.VOICE_ROWS:
            self.assertNotIn(f"| {name} |", block)

    def test_a_voice_model_shows_each_voice_field_after_the_modalities(self) -> None:
        block = render.render_card_block(voice_card())
        names = [line.split(" | ")[0][2:] for line in block.split("\n") if line.startswith("| ")]
        start = names.index("Modalities")
        self.assertEqual(names[start + 1 : start + 10], [name for name, _ in render.VOICE_ROWS])
        self.assertEqual(block.count("\n"), 3 + 20 + len(render.VOICE_ROWS))
        expected = {
            "Voice duplex": "full", "Voice input audio": "16-bit PCM, 16 kHz", "Voice output audio": "16-bit PCM, 24 kHz",
            "Voices": "8", "Voice languages": "en, de",
            "Turn detection": FIXTURE_VOICE["turn_detection"], "Interruption": FIXTURE_VOICE["interruption"],
            "Voice latency": FIXTURE_VOICE["latency"], "Session limit": "30 minutes",
        }
        for name, value in expected.items():
            self.assertEqual(field(block, name), value, name)

    def test_a_voice_value_not_found_reads_unknown_and_pipes_are_escaped(self) -> None:
        voice = {**FIXTURE_VOICE, "latency": None, "languages": [], "voices": None, "interruption": "a | b"}
        block = render.render_card_block(voice_card(voice=voice))
        for name in ("Voice latency", "Voice languages", "Voices"):
            self.assertEqual(field(block, name), "unknown", name)
        self.assertEqual(field(block, "Interruption"), "a \\| b")

    def test_a_voice_price_that_is_not_per_token_shows_its_note(self) -> None:
        pricing = {"input": None, "output": None, "cached_input": None, "notes": "billed per minute of audio"}
        self.assertEqual(
            field(render.render_card_block(voice_card(pricing_usd_per_mtok=pricing)), "Price"),
            "unknown per Mtok; billed per minute of audio",
        )
        self.assertEqual(field(render.render_card_block(card(pricing_usd_per_mtok=pricing)), "Price"), "unknown")
        self.assertEqual(
            field(render.render_card_block(voice_card(pricing_usd_per_mtok={**pricing, "notes": None})), "Price"), "unknown"
        )

    def test_token_formatting(self) -> None:
        self.assertEqual(render._tokens(1_000_000), "1M")
        self.assertEqual(render._tokens(1_500_000), "1.5M")
        self.assertEqual(render._tokens(200_000), "200k")
        self.assertEqual(render._tokens(131_072), "131,072")
        self.assertEqual(render._tokens(None), "unknown")


class ReplaceBlockTest(unittest.TestCase):
    B, E = layout.CARD_BEGIN, layout.CARD_END

    def test_only_the_text_between_the_markers_changes(self) -> None:
        text = f"head\n{self.B}\nold\nolder\n{self.E}\ntail\n"
        self.assertEqual(render.replace_block(text, self.B, self.E, "new\n", "f"), f"head\n{self.B}\nnew\n{self.E}\ntail\n")

    def test_an_empty_pair_is_filled_and_the_result_is_stable(self) -> None:
        text = f"head\n{self.B}\n{self.E}\ntail\n"
        once = render.replace_block(text, self.B, self.E, "x\n", "f")
        self.assertEqual(once, f"head\n{self.B}\nx\n{self.E}\ntail\n")
        self.assertEqual(render.replace_block(once, self.B, self.E, "x\n", "f"), once)

    def test_missing_doubled_and_misordered_markers_are_refused(self) -> None:
        for text in ("no markers\n", f"{self.B}\n", f"{self.E}\n{self.B}\n", f"{self.B}\n{self.E}\n{self.B}\n{self.E}\n"):
            with self.subTest(text=text):
                with self.assertRaisesRegex(ValueError, "^f: needs exactly one"):
                    render.replace_block(text, self.B, self.E, "x\n", "f")


class ModelsTableTest(unittest.TestCase):
    def entries(self, *cards: dict) -> list:
        return [(f"models/example-lab/{c['id']}.json", c) for c in cards]

    def test_no_cards_gives_a_header_and_a_note(self) -> None:
        text = render.render_models_table([])
        self.assertIn("| Model | Maker | Class | Generation | Status | Released | Voice | File |", text)
        self.assertIn("No model cards yet.", text)

    def test_the_row_for_the_fixture_card_links_the_file_beside_its_card(self) -> None:
        text = render.render_models_table(self.entries(card()))
        row = next(line for line in text.split("\n") if line.startswith("| Example Model 1"))
        self.assertEqual(
            row,
            "| Example Model 1 | Example Lab | Example Pro | 1 | ga | 2026-09-01 | - "
            "| [example-lab/example-model-1.md](example-lab/example-model-1.md) |",
        )

    def test_the_voice_column_marks_a_voice_model_by_its_duplex_mode(self) -> None:
        def marker(**voice: object) -> str:
            row = next(l for l in render.render_models_table(self.entries(voice_card(voice={**FIXTURE_VOICE, **voice}))).split("\n") if l.startswith("| Example Voice 1"))
            return row.split(" | ")[6]

        self.assertEqual(marker(duplex="full"), "full-duplex voice")
        self.assertEqual(marker(duplex="half"), "half-duplex voice")
        self.assertEqual(marker(duplex="none"), "voice, no duplex")
        self.assertEqual(marker(duplex=None), "voice")
        text = render.render_models_table(self.entries(card(), voice_card()))
        self.assertEqual(sum("full-duplex voice" in line for line in text.split("\n")), 1)

    def test_unknown_generation_reads_unknown_and_pipes_are_escaped(self) -> None:
        text = render.render_models_table(self.entries(card(generation=None, name="A | B")))
        self.assertIn("| A \\| B | Example Lab | Example Pro | unknown | ga |", text)

    def test_sorted_by_maker_then_newest_release_first(self) -> None:
        cards = [
            card(id="z-old", name="Zed old", maker="Zeta", released="2026-01-01"),
            card(id="a-new", name="Alpha new", maker="alpha", released="2026-09-01"),
            card(id="a-old", name="Alpha old", maker="Alpha", released="2026-03-01"),
        ]
        shuffled = sorted(cards, key=lambda c: c["id"])
        names = [c["name"] for c in sorted(shuffled, key=render._sort_key)]
        self.assertEqual(names, ["Alpha new", "Alpha old", "Zed old"])


class ProvidersTableTest(unittest.TestCase):
    def test_kind_comes_from_the_frontmatter_or_the_first_line_under_the_title(self) -> None:
        self.assertEqual(render.provider_kind("---\nkind: cloud platform\n---\n\n# X\n\nlocal runtime; text\n"), "cloud platform")
        self.assertEqual(render.provider_kind("---\nlast_checked: 2026-10-01\n---\n\n# X\n\nRouter or gateway; more text.\n"), "Router or gateway")
        self.assertEqual(render.provider_kind("# X\n\n**local runtime**; text\n"), "local runtime")
        self.assertEqual(render.provider_kind("# X\n\n## Only a heading\n"), "unknown")

    def test_rows_are_grouped_by_kind_then_title_with_an_unlisted_kind_last(self) -> None:
        rows = [("b.md", "Beta", "local runtime"), ("a.md", "Alpha", "inference host"), ("c.md", "Charlie", "inference host"),
                ("d.md", "Delta", "first-party lab API"), ("e.md", "Echo", "mystery")]
        lines = [line for line in render.render_providers_table(rows).split("\n") if line.startswith("| ") and "---" not in line][1:]
        self.assertEqual([line.split(" | ")[0][2:] for line in lines], ["Delta", "Alpha", "Charlie", "Beta", "Echo"])
        self.assertIn("| Alpha | inference host | [a.md](a.md) |", lines[1])

    def test_no_files_gives_a_note(self) -> None:
        self.assertIn("No provider files yet.", render.render_providers_table([]))


class RenderTiersTest(unittest.TestCase):
    def test_no_placements_gives_the_rules_and_no_rows(self) -> None:
        text = render.render_tiers([], {"version": 1, "placements": {}})
        self.assertIn("last_checked: none\n", text)
        self.assertIn("A row that names no effort covers every effort.", text)
        self.assertIn("No placements yet; every model takes the spec tier.", text)
        self.assertIn("| Model | Effort | Tier | Confidence | Basis | Notes that change a package |", text)

    def test_the_matching_rules_are_all_stated(self) -> None:
        text = render.render_tiers([], {"version": 1, "placements": {}})
        for fragment in (
            "names no effort covers every effort",
            "X and above",
            "takes the next tier down",
            "any quantisation below 4-bit take the spec tier",
            "holds in any harness unless its basis names one",
        ):
            self.assertIn(fragment, text)

    def test_the_header_says_which_files_it_reads(self) -> None:
        text = render.render_tiers([card()], TIERS)
        self.assertIn("`models/<maker>/<id>.json`", text)
        self.assertIn("[implementer-tiers.json](implementer-tiers.json)", text)

    def test_one_row_per_placement_with_basis_and_notes(self) -> None:
        text = render.render_tiers([card()], TIERS)
        rows = [line for line in text.split("\n") if line.startswith("| Example Model 1")]
        self.assertEqual(len(rows), 2)
        basis = "Inferred from the SWE-Bench Pro score [scale-swe-pro-v2]; no hand-off comparison exists."
        notes = "Stops to ask when a scope is unclear unless told it may proceed [scale-swe-pro-v2].; Adds unrequested tests."
        self.assertEqual(rows[0], f"| Example Model 1 | medium and above | outcome | medium | {basis} | {notes} |")
        self.assertTrue(rows[1].startswith("| Example Model 1 | low | design | low |"))
        self.assertIn("last_checked: 2026-10-03\n", text)

    def test_a_placement_without_effort_reads_any_and_no_notes_read_none_recorded(self) -> None:
        data = {"version": 1, "placements": {"example-model-1": {
            "placements": [{"effort": None, "tier": "spec", "confidence": "high"}], "basis": "b", "notes": []}}}
        row = next(line for line in render.render_tiers([card()], data).split("\n") if line.startswith("| Example Model 1"))
        self.assertEqual(row, "| Example Model 1 | any | spec | high | b | none recorded |")

    def test_an_entry_without_placements_adds_no_row(self) -> None:
        data = {"version": 1, "placements": {"example-model-1": {"placements": [], "basis": "", "notes": ["n"]}}}
        self.assertIn("No placements yet", render.render_tiers([card()], data))

    def test_rows_follow_the_card_order_and_a_model_without_a_card_is_named_by_id(self) -> None:
        entry = {"placements": [{"effort": None, "tier": "spec", "confidence": "low"}], "basis": "b", "notes": []}
        cards = [card(id="a", name="Alpha", maker="A"), card(id="b", name="Beta", maker="B")]
        data = {"version": 1, "placements": {"b": entry, "ghost": entry, "a": entry}}
        names = [line.split(" | ")[0][2:] for line in render.render_tiers(cards, data).split("\n") if " | spec | " in line]
        self.assertEqual(names, ["Alpha", "Beta", "ghost"])


class RenderLinkSafetyTest(unittest.TestCase):
    MODEL = "models/example-lab/example-model-1.md"

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name) / "repo"
        self.outside = Path(self._tmp.name) / "outside"
        self.outside.mkdir()
        build_repo(self.root)
        # Make every generated file stale, so a render has something to write.
        stale = layout.CARD_BEGIN + layout.CARD_END + layout.MODELS_BEGIN + layout.MODELS_END
        for rel in (layout.MODELS_README, layout.TIERS_MD, self.MODEL):
            (self.root / rel).write_text("---\n---\n" + stale, encoding="utf-8")

    def stale(self, rel: str) -> bool:
        return (self.root / rel).read_text(encoding="utf-8").startswith("---\n---\n")

    def test_a_linked_output_file_is_refused_and_its_target_left_alone(self) -> None:
        target = self.outside / "target.txt"
        target.write_text("keep me\n", encoding="utf-8")
        (self.root / layout.TIERS_MD).unlink()
        os.symlink(target, self.root / layout.TIERS_MD)
        self.assertEqual(quiet_main("--root", str(self.root)), 1)
        self.assertEqual(target.read_text(encoding="utf-8"), "keep me\n")
        self.assertTrue((self.root / layout.TIERS_MD).is_symlink())
        self.assertTrue(self.stale(layout.MODELS_README), "nothing is written when one destination is refused")
        self.assertTrue(self.stale(self.MODEL))

    def test_a_linked_model_file_is_refused_and_nothing_else_written(self) -> None:
        target = self.outside / "target.txt"
        target.write_text(layout.CARD_BEGIN + layout.CARD_END, encoding="utf-8")
        (self.root / self.MODEL).unlink()
        os.symlink(target, self.root / self.MODEL)
        self.assertEqual(quiet_main("--root", str(self.root)), 1)
        self.assertEqual(target.read_text(encoding="utf-8"), layout.CARD_BEGIN + layout.CARD_END)
        self.assertTrue(self.stale(layout.TIERS_MD))

    def test_a_dangling_link_at_an_output_file_is_refused(self) -> None:
        (self.root / layout.TIERS_MD).unlink()
        os.symlink(self.outside / "not-yet", self.root / layout.TIERS_MD)
        self.assertEqual(quiet_main("--root", str(self.root)), 1)
        self.assertFalse((self.outside / "not-yet").exists())

    def test_a_linked_output_folder_is_refused_and_its_target_left_alone(self) -> None:
        shutil.rmtree(self.root / "applications")
        os.symlink(self.outside, self.root / "applications")
        self.assertEqual(quiet_main("--root", str(self.root)), 1)
        self.assertEqual(list(self.outside.iterdir()), [])

    def test_a_link_swapped_in_after_the_check_is_still_not_followed(self) -> None:
        target = self.outside / "target.txt"
        target.write_text("keep me\n", encoding="utf-8")
        real = render.safefs.refuse_links
        calls = []

        def swap(root: Path, rel: str, folder: bool = False) -> None:
            real(root, rel, folder)
            calls.append(rel)
            if len(calls) == 4:  # every check has passed; put a link where the last file goes
                (root / rel).unlink()
                os.symlink(target, root / rel)

        with mock.patch.object(render.safefs, "refuse_links", swap):
            self.assertEqual(quiet_main("--root", str(self.root)), 1)
        self.assertEqual(calls[-1], layout.TIERS_MD)
        self.assertEqual(target.read_text(encoding="utf-8"), "keep me\n")

    def test_a_plain_destination_is_replaced_in_place(self) -> None:
        self.assertEqual(quiet_main("--root", str(self.root)), 0)
        self.assertTrue((self.root / layout.TIERS_MD).read_text(encoding="utf-8").startswith("---\nlast_checked: 2026-10-03"))

    def test_a_missing_applications_folder_is_created(self) -> None:
        shutil.rmtree(self.root / "applications")
        self.assertEqual(quiet_main("--root", str(self.root)), 0)
        self.assertTrue((self.root / layout.TIERS_MD).is_file())


class RenderFilesTest(unittest.TestCase):
    def test_card_files_read_makers_folders_and_name_a_bad_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            write(root, "models/example-lab/example-model-1.json", json.dumps(card()))
            self.assertEqual([(p, c["id"]) for p, c in render.card_files(root)], [("models/example-lab/example-model-1.json", "example-model-1")])
            self.assertEqual([c["id"] for c in render.load_cards(root)], ["example-model-1"])
            write(root, "models/example-lab/broken.json", "{not json")
            with self.assertRaisesRegex(ValueError, r"models/example-lab/broken\.json: not readable JSON"):
                render.card_files(root)

    def test_render_all_covers_the_blocks_the_two_tables_and_the_placements(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = build_repo(Path(tmp))
            files = render.render_all(root)
            self.assertEqual(
                sorted(files),
                ["applications/implementer-tiers.md", "models/README.md", "models/example-lab/example-model-1.md", "providers/README.md"],
            )
            self.assertIn("Example Model 1", files["models/README.md"])
            self.assertIn("Example Host | inference host", files["providers/README.md"])

    def test_text_outside_the_markers_is_kept(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = build_repo(Path(tmp))
            path = root / "models/example-lab/example-model-1.md"
            path.write_text(path.read_text(encoding="utf-8") + "\nWritten by hand.\n", encoding="utf-8")
            self.assertTrue(render.render_all(root)["models/example-lab/example-model-1.md"].endswith("\nWritten by hand.\n"))

    def test_a_card_without_a_model_file_is_skipped_and_a_file_without_markers_stops_the_run(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            write(root, "models/example-lab/example-model-1.json", json.dumps(card()))
            self.assertNotIn("models/example-lab/example-model-1.md", render.render_all(root))
            write(root, "models/example-lab/example-model-1.md", "# No markers\n")
            with self.assertRaisesRegex(ValueError, r"example-model-1\.md: needs exactly one"):
                render.render_all(root)
            self.assertEqual(quiet_main("--root", tmp), 1)

    def test_a_readme_without_its_table_markers_stops_the_run(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = build_repo(Path(tmp))
            write(root, layout.PROVIDERS_README, "# Providers\n")
            with self.assertRaisesRegex(ValueError, r"providers/README\.md: needs exactly one"):
                render.render_all(root)

    def test_main_is_idempotent(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = build_repo(Path(tmp))
            first = {rel: (root / rel).read_text(encoding="utf-8") for rel in render.render_all(root)}
            self.assertEqual(quiet_main("--root", str(root)), 0)
            self.assertEqual(first, {rel: (root / rel).read_text(encoding="utf-8") for rel in first})
            out = io.StringIO()
            with contextlib.redirect_stdout(out):
                self.assertEqual(render.main(["--root", str(root)]), 0)
            self.assertIn("0 written", out.getvalue())

    def test_main_with_no_cards_still_writes_the_placements_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            self.assertEqual(quiet_main("--root", tmp), 0)
            self.assertIn("No placements yet", (Path(tmp) / layout.TIERS_MD).read_text(encoding="utf-8"))

    def test_main_reports_a_bad_card_and_a_bad_placements_file_and_exits_1(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            write(Path(tmp), "models/x/bad.json", "[]")
            self.assertEqual(quiet_main("--root", tmp), 1)
        with tempfile.TemporaryDirectory() as tmp:
            write(Path(tmp), layout.TIERS_JSON, "{")
            self.assertEqual(quiet_main("--root", tmp), 1)
            write(Path(tmp), layout.TIERS_JSON, "[]")
            self.assertEqual(quiet_main("--root", tmp), 1)

    def test_a_provider_added_shows_in_the_table_after_a_render(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = build_repo(Path(tmp))
            provider_file(root, "second", "Second Host", "local runtime")
            self.assertEqual(quiet_main("--root", str(root)), 0)
            self.assertIn("| Second Host | local runtime | [second.md](second.md) |", (root / layout.PROVIDERS_README).read_text(encoding="utf-8"))

    def test_a_second_model_file_gets_its_own_block(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = build_repo(Path(tmp))
            model_files(root, card=card(id="other-1", name="Other 1"))
            self.assertEqual(quiet_main("--root", str(root)), 0)
            self.assertIn("`other-1`", (root / "models/example-lab/other-1.md").read_text(encoding="utf-8"))
            self.assertNotIn("`other-1`", (root / "models/example-lab/example-model-1.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
